---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

```

Ctrl - I  helps with alignment

```{r}
# "Let"s write code with a \"quote"" 
```

```{r}

amount_spent <- c(9.1,8.55,14.32,14.17,14.34,7.97,9.79,11.47,12.44)

spending_category <- c("Lunch", "Dinner", "Lunch", "Lunch", "Cinema", "Drinks",
                       "Lunch", "Lunch", "Dinner")

my_week_of_spending <- tibble(amount_spent, spending_category = category)

my_week_of_spending %>% 
  summarise(sum(amount_spent))

summarise(filter(my_week_of_spending, spending_category == "Lunch"), 
          sum(amount_spent)
)
```

```{r}
library(styler) # handy tool to tidy up code - addin menu above then style selection

AmountSpent <- c(9.1, 8.55, 14.32, 14.17, 14.34, 7.97, 9.79, 11.47, 12.44)
Category <- c(
  "Lunch",
  "Dinner",
  "Lunch",
  "Lunch",
  "Cinema",
  "Drinks",
  "Lunch",
  "Lunch",
  "Dinner"
)
my.week.of.spending <- tibble(AmountSpent = AmountSpent, SpendingCategory = Category)
str(my.week.of.spending)
View(my.week.of.spending)
my.week.of.spending
summarise(my.week.of.spending, sum(AmountSpent))
summarise(filter(my.week.of.spending, SpendingCategory == "Lunch"), sum(AmountSpent))
```

```{r}
library(skimr)
skim(mtcars) 
```

